/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.finalproject;

import static com.mycompany.finalproject.frm_login.password;
import static com.mycompany.finalproject.frm_login.user;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author nurefsanalbas
 */
public class frm_welcome extends javax.swing.JFrame {

    ImageIcon imageAnimals = new ImageIcon("dog.png");
    ImageIcon imagePlants = new ImageIcon("plant.png");

    public frm_welcome() {
        initComponents();
        this.setLocationRelativeTo(null);
        lbl_animals.setIcon(imageAnimals);
        lbl_plants.setIcon(imagePlants);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbd_choices = new javax.swing.JTabbedPane();
        pnl_welcome = new javax.swing.JPanel();
        lbl_welcome = new javax.swing.JLabel();
        btn_animals = new javax.swing.JButton();
        btn_plants = new javax.swing.JButton();
        lbl_animals = new javax.swing.JLabel();
        lbl_plants = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        pnl_user = new javax.swing.JPanel();
        lbl_user = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        lbl_nameSurname = new javax.swing.JLabel();
        txt_nameSurname = new javax.swing.JTextField();
        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        lbl_tel = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        lbl_adress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_adress = new javax.swing.JTextArea();
        lbl_image = new javax.swing.JLabel();
        lbl_department = new javax.swing.JLabel();
        txt_department = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        tbd_choices.setPreferredSize(new java.awt.Dimension(751, 550));

        pnl_welcome.setBackground(new java.awt.Color(204, 204, 255));
        pnl_welcome.setMinimumSize(new java.awt.Dimension(730, 504));
        pnl_welcome.setPreferredSize(new java.awt.Dimension(730, 504));

        lbl_welcome.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        lbl_welcome.setText("Welcome, which genre's records would you like to view?");

        btn_animals.setText("ANİMALS");
        btn_animals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_animalsActionPerformed(evt);
            }
        });

        btn_plants.setText("PLANTS");
        btn_plants.setMaximumSize(new java.awt.Dimension(101, 29));
        btn_plants.setMinimumSize(new java.awt.Dimension(101, 29));
        btn_plants.setPreferredSize(new java.awt.Dimension(101, 29));
        btn_plants.setSize(new java.awt.Dimension(101, 29));
        btn_plants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_plantsActionPerformed(evt);
            }
        });

        btn_back.setText("<--");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_welcomeLayout = new javax.swing.GroupLayout(pnl_welcome);
        pnl_welcome.setLayout(pnl_welcomeLayout);
        pnl_welcomeLayout.setHorizontalGroup(
            pnl_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_welcomeLayout.createSequentialGroup()
                .addGroup(pnl_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_welcomeLayout.createSequentialGroup()
                        .addGroup(pnl_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_welcomeLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(lbl_animals, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_welcomeLayout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(btn_animals)))
                        .addGroup(pnl_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_welcomeLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(lbl_plants, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_welcomeLayout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(btn_plants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnl_welcomeLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lbl_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_welcomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_back)
                .addGap(27, 27, 27))
        );
        pnl_welcomeLayout.setVerticalGroup(
            pnl_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_welcomeLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbl_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(pnl_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_plants, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(btn_animals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_animals, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_plants, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_back)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        tbd_choices.addTab("CHOİCES", pnl_welcome);

        pnl_user.setBackground(new java.awt.Color(204, 204, 255));

        lbl_user.setText("Username:");

        lbl_password.setText("Password:");

        lbl_nameSurname.setText("Name Surname:");

        lbl_id.setText("ID:");

        lbl_email.setText("Email:");

        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        lbl_tel.setText("Telephone Number:");

        lbl_adress.setText("Adress:");

        txta_adress.setColumns(20);
        txta_adress.setRows(5);
        jScrollPane1.setViewportView(txta_adress);

        lbl_image.setText("İMAGE");

        lbl_department.setText("Department:");

        javax.swing.GroupLayout pnl_userLayout = new javax.swing.GroupLayout(pnl_user);
        pnl_user.setLayout(pnl_userLayout);
        pnl_userLayout.setHorizontalGroup(
            pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_userLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_userLayout.createSequentialGroup()
                        .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_userLayout.createSequentialGroup()
                                .addComponent(lbl_adress)
                                .addGap(386, 386, 386)
                                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_userLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lbl_id)))
                        .addContainerGap(183, Short.MAX_VALUE))
                    .addGroup(pnl_userLayout.createSequentialGroup()
                        .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_userLayout.createSequentialGroup()
                                .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnl_userLayout.createSequentialGroup()
                                        .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_nameSurname)
                                            .addComponent(lbl_user, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnl_userLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnl_userLayout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_nameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(pnl_userLayout.createSequentialGroup()
                                        .addComponent(lbl_tel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_userLayout.createSequentialGroup()
                                        .addComponent(lbl_department)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_department, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnl_userLayout.createSequentialGroup()
                                        .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_password)
                                            .addComponent(lbl_email))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_mail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(132, 132, 132)
                                .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_userLayout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnl_userLayout.setVerticalGroup(
            pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_userLayout.createSequentialGroup()
                .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_userLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_id)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nameSurname)
                            .addComponent(txt_nameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_user)
                            .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_password)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_email)
                            .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_department)
                            .addComponent(txt_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tel)
                            .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_userLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnl_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_adress)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        tbd_choices.addTab("USER", pnl_user);

        getContentPane().add(tbd_choices);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_animalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_animalsActionPerformed
        frm_animals frm = new frm_animals();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_animalsActionPerformed

    private void btn_plantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_plantsActionPerformed
        frm_plants frm = new frm_plants();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btn_plantsActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        frm_login frm = new frm_login();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed

        Update();

    }//GEN-LAST:event_btn_updateActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        txt_username.setText(frm_login.user);
        txt_password.setText(frm_login.password);

        GetDataWihtUsername(txt_username.getText(), txt_password.getText());

    }//GEN-LAST:event_formWindowOpened

    public void GetDataWihtUsername(String username, String password) {

        try {
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/ANIMALS", "APP", "as");
            Statement stmt = conn.createStatement();
            String query = "SELECT * FROM USERS WHERE USERNAME='" + username + "' AND PASSWORD='" + password + "'";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {

                int id = rs.getInt("ID");
                String nameSurname = rs.getString("NAMESURNAME");
                String email = rs.getString("EMAIL");
                String department = rs.getString("DEPARTMENT");
                String telnumber = rs.getString("TELNUMBER");
                String adress = rs.getString("ADRESS");
                String image = rs.getString("IMAGE");

                txt_id.setText(id + "");
                txt_nameSurname.setText(nameSurname);
                txt_mail.setText(email);
                txta_adress.setText(adress);
                txt_department.setText(department);
                txt_tel.setText(telnumber);
                lbl_image.setText(image);

            }

            conn.close();

        } catch (SQLException e) {

            e.printStackTrace();
        }

    }

    public boolean Update() {

        boolean rvalue = false;
        Connection conn = null;
        try {
            int id = Integer.parseInt(txt_id.getText());
            String nameSurname = txt_nameSurname.getText();
            String email = txt_mail.getText();
            String password = txt_password.getText();
            String adress = txta_adress.getText();
            String telnumber = txt_tel.getText();
            String department = txt_department.getText();
            String username = txt_username.getText();
            String image = lbl_image.getText();

            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/ANIMALS", "APP", "as");
            Statement stmt = conn.createStatement();
            String query = "UPDATE USERS SET NAMESURNAME='" + nameSurname + "', EMAIL='" + email
                    + "', PASSWORD='" + password + "', ADRESS='" + adress + "', USERNAME= '" + username + "', TELNUMBER='"
                    + telnumber + "',IMAGE= '" + image + "' WHERE ID=" + id;

            if (Pattern.matches("[a-zA-Z0-9]{3}", password)) {
                JOptionPane.showMessageDialog(rootPane, "It's succesfully updated...");
            } else {
                JOptionPane.showMessageDialog(rootPane, "İnvalid Password!,please input valid Password...");
            }

            stmt.executeUpdate(query);
            conn.close();
            rvalue = true;

        } catch (SQLException ex) {
            Logger.getLogger(frm_animals.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if (conn != null && !(conn.isClosed())) {
                conn.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(frm_animals.class.getName()).log(Level.SEVERE, null, ex);

        }
        return rvalue;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_animals;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_plants;
    private javax.swing.JButton btn_update;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_adress;
    private javax.swing.JLabel lbl_animals;
    private javax.swing.JLabel lbl_department;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_nameSurname;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_plants;
    private javax.swing.JLabel lbl_tel;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JPanel pnl_user;
    private javax.swing.JPanel pnl_welcome;
    private javax.swing.JTabbedPane tbd_choices;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_nameSurname;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_tel;
    private javax.swing.JTextField txt_username;
    private javax.swing.JTextArea txta_adress;
    // End of variables declaration//GEN-END:variables
}
