/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.finalproject;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author nurefsanalbas
 */
public class frm_registration extends javax.swing.JFrame {

    String image;//I took an image variable to take photos

    /**
     * Creates new form frm_registration
     */
    public frm_registration() {
        initComponents();
        lbl_pass.setVisible(false);
        lbl_usern.setVisible(false);//I used label to notify user with regex.
        //I made it invisible when user is not logged in to make it visible in case of error or positive feedback 
        lbl_mail.setVisible(false);
        lbl_tel.setVisible(false);
        lbl_name.setVisible(false);
        lbl_address.setVisible(false);
        setLocationRelativeTo(null);//I set frame on the middle of the page.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_registration = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_nameSurname = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_department = new javax.swing.JLabel();
        lbl_telNumber = new javax.swing.JLabel();
        lbl_adress = new javax.swing.JLabel();
        txt_nameSurname = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_department = new javax.swing.JTextField();
        txt_telnumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_adress = new javax.swing.JTextArea();
        btn_save = new javax.swing.JButton();
        lbl_image = new javax.swing.JLabel();
        btn_choose = new javax.swing.JButton();
        lbl_name = new javax.swing.JLabel();
        lbl_usern = new javax.swing.JLabel();
        lbl_pass = new javax.swing.JLabel();
        lbl_mail = new javax.swing.JLabel();
        lbl_tel = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        lbl_address = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_registration.setBackground(new java.awt.Color(102, 111, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USER REGISTRATION FORM ");

        lbl_nameSurname.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_nameSurname.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nameSurname.setText("Name Surname:");

        lbl_username.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setText("Username:");

        lbl_id.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id.setText("ID:");

        lbl_password.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(255, 255, 255));
        lbl_password.setText("Password:");

        lbl_email.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_email.setText("Email:");

        lbl_department.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_department.setForeground(new java.awt.Color(255, 255, 255));
        lbl_department.setText("Department:");

        lbl_telNumber.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_telNumber.setForeground(new java.awt.Color(255, 255, 255));
        lbl_telNumber.setText("Telephone Number:");

        lbl_adress.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_adress.setForeground(new java.awt.Color(255, 255, 255));
        lbl_adress.setText("Address:");

        txta_adress.setColumns(20);
        txta_adress.setRows(5);
        jScrollPane1.setViewportView(txta_adress);

        btn_save.setText("SAVE");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        lbl_image.setForeground(new java.awt.Color(255, 255, 255));
        lbl_image.setText("             IMAGE AREA");

        btn_choose.setText("CHOOSE IMAGE");
        btn_choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chooseActionPerformed(evt);
            }
        });

        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setText("lbl");

        lbl_usern.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usern.setText("lbl");

        lbl_pass.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pass.setText("lbl");

        lbl_mail.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mail.setText("lbl");

        lbl_tel.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tel.setText("lbl");

        btn_back.setText("<--");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        lbl_address.setForeground(new java.awt.Color(255, 255, 255));
        lbl_address.setText("lbl");

        javax.swing.GroupLayout pnl_registrationLayout = new javax.swing.GroupLayout(pnl_registration);
        pnl_registration.setLayout(pnl_registrationLayout);
        pnl_registrationLayout.setHorizontalGroup(
            pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registrationLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btn_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_telNumber)
                    .addComponent(lbl_adress)
                    .addComponent(lbl_nameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_username)
                    .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_password)
                    .addComponent(lbl_email)
                    .addComponent(lbl_department))
                .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_registrationLayout.createSequentialGroup()
                        .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_registrationLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nameSurname)
                                    .addComponent(txt_username)
                                    .addComponent(txt_password)
                                    .addComponent(txt_id)
                                    .addComponent(txt_email)
                                    .addComponent(txt_department, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt_telnumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_pass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_usern, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_tel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_mail, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(pnl_registrationLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_registrationLayout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(pnl_registrationLayout.createSequentialGroup()
                        .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_registrationLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_choose)
                                    .addGroup(pnl_registrationLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(btn_save))))
                            .addGroup(pnl_registrationLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_address)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnl_registrationLayout.setVerticalGroup(
            pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registrationLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_registrationLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(btn_choose)
                        .addGap(18, 18, 18)
                        .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_registrationLayout.createSequentialGroup()
                                .addComponent(btn_back)
                                .addGap(16, 16, 16))
                            .addGroup(pnl_registrationLayout.createSequentialGroup()
                                .addComponent(btn_save)
                                .addGap(88, 88, 88))))
                    .addGroup(pnl_registrationLayout.createSequentialGroup()
                        .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_address)
                            .addGroup(pnl_registrationLayout.createSequentialGroup()
                                .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnl_registrationLayout.createSequentialGroup()
                                        .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_nameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txt_nameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbl_name)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbl_username)
                                            .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_usern))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbl_id)
                                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbl_password)
                                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_pass))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbl_email)
                                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_mail))
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_department))
                                    .addComponent(txt_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_tel)
                                    .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_telnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_telNumber)))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_adress))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        getContentPane().add(pnl_registration, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        int id = Integer.parseInt(txt_id.getText());//I turned id to integer.
        String username = txt_username.getText();//I retrive txt_username textfield's text and assign to username.
        String password = txt_password.getText();//I retrive txt_password textfield's text and assign to password.
        String nameSurname = txt_nameSurname.getText();//I retrive txt_nameSurname textfield's text and assign to nameSurname.
        String email = txt_email.getText();//I retrive txt_email textfield's text and assign to email.
        String department = txt_department.getText();//I retrive txt_department textfield's text and assign to department.
        String telnumber = txt_telnumber.getText();//I retrive txt_telnumber textfield's text and assign to telnumber.
        String adress = txta_adress.getText();//I retrive txta_adress textfield's text and assign to adress.

        if (Control()) {//I called regex function "Control()" here. If function returns true, user can inserted.

            insertUser(id, username, password, nameSurname, email, department, telnumber, adress, image);//User insert with this function.
            JOptionPane.showMessageDialog(rootPane, "It's succesfuly inserted...");//If it inserted succesfuly user retrieve this message.
        
        }

    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chooseActionPerformed
        JFileChooser fc = new JFileChooser();//I made a new fileChooser.
        fc.showOpenDialog(null);//I opened my file selection window
        File file = fc.getSelectedFile();//I assigned the file marked from the file selection window to my file field.
        image = file.getAbsolutePath();//I retrieve file's path and assign to image.

        ImageIcon imageIcon = new ImageIcon(new ImageIcon(image).getImage().
                getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH));//I created an ImageIcon and I called image here.
        lbl_image.setIcon(imageIcon);//getScaledInstance function scales the image.
        //I set lbl_image imageIcon.
    }//GEN-LAST:event_btn_chooseActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        //I turn to login form here.
        frm_login frm = new frm_login();
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_btn_backActionPerformed

    public boolean insertUser(int id, String username, String password, String nameSurname,
            String email, String department, String telnumber, String adress, String image) {

        boolean rvalue = false;//I took a rvalue variable.
        Connection conn = null;//I used this interface because it is used to communicate with the database with all its methods.
        try {

            Statement stmt = null;
            //I have defined the statement that defines the various methods to send the interface sql commands to the database.
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/ANIMALS", "APP", "as");//I wrote database URL, password and username.
            stmt = conn.createStatement();

            String query = "INSERT INTO USERS VALUES(" + id + ",'" + username + "','" + password + "','"
                    + nameSurname + "','" + email + "','" + department + "','" + telnumber + "','" + adress + "','" + image + "')";
            //I insert into users some values with the Insert command.
            stmt.executeUpdate(query);//It runs query.

            conn.close();// Database connection closed.
            rvalue = true;//If everything true until here, rvalue equals true.
        } catch (SQLException ex) {

            Logger.getLogger(frm_registration.class.getName()).log(Level.SEVERE, null, ex);//Catches the error when the connection cannot be established.

        }
        try {
            if (conn != null && !(conn.isClosed())) {//if connection isn't null or closed
                conn.close();//we closed connection
            }
        } catch (SQLException ex) {
            Logger.getLogger(frm_registration.class.getName()).log(Level.SEVERE, null, ex);//Catches the error when the connection cannot be established.

        }

        return rvalue;//It returns true;

    }

    public boolean Control() {
        boolean rvalue = true; //I took a rvalue variable.
        Matcher matcher; //I took matcher variable to match.
        if (txt_nameSurname.getText().isEmpty()) {//If txt_nameSurname is empty,
            JOptionPane.showMessageDialog(rootPane, "Name Surname mustn't be empty");//I turned this message.
            rvalue = false;//Its wrong so rvalue returns false.

        } else {
            matcher = Pattern.compile("^[a-zA-Z//s]{4,}").matcher(txt_nameSurname.getText());
            //Name surname should be at least 4 charachter and it should be start with a word.
            if (!matcher.find()) {//if matcher couldn't find appropriate text,
                JOptionPane.showMessageDialog(rootPane, "Name should be like Efsan Albas");//It shows message like that.
                lbl_name.setText("-");//If it's wrong, I set text '-'
                lbl_name.setVisible(true);//Its shows "-"
                rvalue = false;//Its wrong so rvalue returns false.
            } else {
                lbl_name.setText("+");//If it's true, I set text '+'.
                lbl_name.setVisible(true);//true conditions it shows "+".

            }
        }

        if (txt_password.getText().isEmpty()) {//If txt_password is empty,
            JOptionPane.showMessageDialog(rootPane, "Password not be empty");//I turned this message.

            rvalue = false;//Its wrong so rvalue returns false.

        } else {
            matcher = Pattern.compile("^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{6,}$").matcher(txt_password.getText());
            //?= everything in parentheses must come after the match caught. 
            //.* searches everything in front of it and password should have numbers and digits it should be bigger than 6 character.
            if (!matcher.find()) {//if matcher couldn't find appropriate text,
                JOptionPane.showMessageDialog(rootPane, "Password should be like 12345e");//It shows message like that.

                lbl_pass.setText("-");//If it's wrong, I set text '-'
                lbl_pass.setVisible(true);//Its shows "-"
                rvalue = false;//Its wrong so rvalue returns false.

            } else {
                lbl_pass.setText("+");//If it's true, I set text '+'.
                lbl_pass.setVisible(true);//true conditions it shows "+".

            }

        }
        if (txt_username.getText().isEmpty()) {//If txt_username is empty,
            JOptionPane.showMessageDialog(rootPane, "Username mustn't be empty");//I turned this message.
            rvalue = false;//Its wrong so rvalue returns false.

        } else {
            matcher = Pattern.compile("^(.*[A-Za-z]{4,})(.*[0-9]{1,}$)").matcher(txt_username.getText());
            //.* searches everything in front of it
            //Username should include at least four letter and 1 digit
            if (!matcher.find()) {//if matcher couldn't find appropriate text,
                JOptionPane.showMessageDialog(rootPane, "Username should be like efsan34");//It shows message like that.
                lbl_usern.setText("-");//If it's wrong, I set text '-'
                lbl_usern.setVisible(true);//Its shows "-"
                rvalue = false;//Its wrong so rvalue returns false.
            } else {
                lbl_usern.setText("+");//If it's true, I set text '+'.
                lbl_usern.setVisible(true);//true conditions it shows "+".

            }
        }

        if (txt_email.getText().isEmpty()) {//If txt_email is empty,
            JOptionPane.showMessageDialog(rootPane, "Email mustn't be empty");//I turned this message.
            rvalue = false;//Its wrong so rvalue returns false.

        } else {
            matcher = Pattern.compile("^(.*[\\w][\\w\\d])@(gmail|hotmail)(.com)$").matcher(txt_email.getText());
            //Email should include firstly letter than digit and  gmail or hotmail.com
            if (!matcher.find()) {//if matcher couldn't find appropriate text,
                JOptionPane.showMessageDialog(rootPane, "Email should be like nurefsan34@gmail.com");//It shows message like that.
                lbl_mail.setText("-");//If it's wrong, I set text '-'
                lbl_mail.setVisible(true);//Its shows "-"
                rvalue = false; //Its wrong so rvalue returns false.

            } else {
                lbl_mail.setText("+");//If it's true, I set text '+'.
                lbl_mail.setVisible(true);//true conditions it shows "+".

            }
        }
        if (txt_telnumber.getText().isEmpty()) {//If txt_telnumber is empty,
            JOptionPane.showMessageDialog(rootPane, "Telephone number mustn't be empty");//I turned this message.
            rvalue = false;//Its wrong so rvalue returns false.
        } else {
            matcher = Pattern.compile("^(\\+[1-9][0-9]?)\\-([0-9]{10})$").matcher(txt_telnumber.getText());
            //telephone number should start with '+' and it should be 10 character.
            if (!matcher.find()) {//if matcher couldn't find appropriate text,
                JOptionPane.showMessageDialog(rootPane, "Telephone number should be like +90-4565434549");//It shows message like that.
                lbl_tel.setText("-");//If it's wrong, I set text '-'
                lbl_tel.setVisible(true);//Its shows "-"
                rvalue = false;//Its wrong so rvalue returns false.

            } else {
                lbl_tel.setText("+");//If it's true, I set text '+'.
                lbl_tel.setVisible(true);//true conditions it shows "+".

            }
        }
        if (txta_adress.getText().isEmpty()) {//If txta_adress is empty,
            JOptionPane.showMessageDialog(rootPane, "Adress mustn't be empty");//I turned this message.
            rvalue = false;//Its wrong so rvalue returns false.
        } else {
            matcher = Pattern.compile("[\\w\\s](\\d)?").matcher(txta_adress.getText());
            //Adress should be like "Yıldız mahallesi Ankara/Demetevler".
            if (!matcher.find()) {//if matcher couldn't find appropriate text,
                JOptionPane.showMessageDialog(rootPane, "Adress should be like Yıldız mahallesi Ankara/Demetevler");//It shows message like that.
                lbl_address.setText("-");//If it's wrong, I set text '-'
                lbl_address.setVisible(true);//Its shows "-"
                rvalue = false;//Its wrong so rvalue returns false.

            } else {
                lbl_address.setText("+");//If it's true, I set text '+'.
                lbl_address.setVisible(true);//true conditions it shows "+".

            }
        } 
        return rvalue;//In true conditions I turned rvalue.
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_choose;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_adress;
    private javax.swing.JLabel lbl_department;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_id;
    public javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_nameSurname;
    private javax.swing.JLabel lbl_pass;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_tel;
    private javax.swing.JLabel lbl_telNumber;
    private javax.swing.JLabel lbl_usern;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pnl_registration;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nameSurname;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_telnumber;
    private javax.swing.JTextField txt_username;
    private javax.swing.JTextArea txta_adress;
    // End of variables declaration//GEN-END:variables
}
